spring:
  datasource:
    # Change DESKTOP-F879KH9 to your SQL server name
    url: jdbc:sqlserver://hn.database.windows.net:1433;database=test;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: 'hazy@hn'
    password: '@h0917815161'

server:
  port: 8082